fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Entity\User
  service:
    mailer: fos_user.mailer.noop
  from_email:
    address: '%env(resolve:USER_ADDRESS)%'
    sender_name: '%env(resolve:SENDER_NAME)%'
